version: "3.8"
services:
  runner:
    image: docker.io/gitea/act_runner:latest
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "${INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "gitea-default-runner"
    volumes:
      - runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../config/gitea-runner/config.yaml:/config.yaml
    restart: always
    extra_hosts:
      - "${INSTANCE_DOMAIN}:${INSTANCE_IP}"
    network_mode: host

volumes:
  runner-data:
